### ISSUE TITLE
Registering Good before routing means no route logs?

### ISSUE THREAD

**Issue by achingbrain** [hapijs/good#360]
If I do this sort of thing:

```javascript
var Hapi = require('hapi');
var Good = require('good');
var GoodConsole = require('good-console');

var server = new Hapi.Server();

server.connection({
  port: 10983
});

server.route({
  method: ['GET'],
  path: '/',
  handler: function (request, reply) {
    server.log([], 'In handler (server.log)');
    request.log([], 'In handler (request.log)');

    reply('handled!');
  }
});

server.register({
  register: Good,
  options: {
    reporters: [{
      reporter: GoodConsole,
      events: {
        error: '*',
        log: '*',
        request: '*',
        response: '*'
      }
    }]
  }
}, function () {
  server.log([], 'Registered good');

  server.start(function () {
    server.log([], 'Server started');
  });
});
```

When starting the app and hitting port 10983 I see this in the console:

```
150610/123724.153, [log], data: Registered good
150610/123724.166, [log], data: Server started
150610/123728.128, [log], data: In handler (server.log)
150610/123728.128, [request], data: In handler (request.log)
150610/123728.124, [response], http://localhost:10983: get / {} 200 (11ms) 
```

If, however I create the server connection and do the routing after registering Good like this:

```javascript
var Hapi = require('hapi');
var Good = require('good');
var GoodConsole = require('good-console');

var server = new Hapi.Server();

server.register({
  register: Good,
  options: {
    reporters: [{
      reporter: GoodConsole,
      events: {
        error: '*',
        log: '*',
        request: '*',
        response: '*'
      }
    }]
  }
}, function () {
  server.log([], 'Registered good');
  
  server.connection({
    port: 10983
  });
  server.route({
    method: ['GET'],
    path: '/',
    handler: function (request, reply) {
      server.log([], 'In handler (server.log)');
      request.log([], 'In handler (request.log)');

      reply('handled!');
    }
  });

  server.start(function () {
    server.log([], 'Server started');
  });
});
```

...then hitting the handler shows this in the console:

```
150610/123745.594, [log], data: Registered good
150610/123745.627, [log], data: Server started
150610/123747.720, [log], data: In handler (server.log)
```

e.g. the `request` and `response` log lines are missing.

Is this by design?  Is there a way to register Good so that it receives all log events event if it was registered before performing routing?

**Comment by arb** [comment]
Sorry, I haven't had a chance to look at this yet.

**Comment by kevinmstephens** [comment]
As `request.log` is a connection event you have to have connections registered before you register Good. The other logging events are stashed at `server._events` and are not related to connections, so that's why they still work.

The key logic is here: https://github.com/hapijs/hapi/blob/master/lib/plugin.js#L22

**Comment by kevinmstephens** [comment]
As request.log is a connection event you have to have connections registered before you register Good. The other logging events are stashed at server._events and are not related to connections, so that's why they still work.

The key logic is here: https://github.com/hapijs/hapi/blob/master/lib/plugin.js#L22

Could potentially check for when a Good consumer tries to use request logging when their are no connections registered and throw an error.

**Comment by kevinmstephens** [comment]
@achingbrain It's the `server.connection` that must be made prior, not the routes.
