### ISSUE TITLE
Readme.md doesn't explain what does this library do

### ISSUE THREAD

**Issue by mik01aj** [hapijs/good#369]
I know I can install and test it, but I'd actually expect to find this info in the README.

* Why do I need Good? Does it create logs, or does it just emit some events I can handle?
* Why would these events be better than Hapi events?
* Why would I want to use Good instead of e.g. Winston?
* does it make sense to use it without Hapi? (i.e. is it an independent library, or just a Hapi plugin?)

You provide code examples, but don't provide information what's supposed to happen when I run them. You provide documentation of some minor API functions, but you don't explain the goal of the whole library. It doesn't become clear just by looking on your picture of a piece of wood with an antenna.

**Comment by arb** [comment]
It emits an "ops" event and also listens for several critical hapi events and creates useful logging information from them. The "ops" event includes important sys admin information like memory usage and network latency. 

These events are piped through "reporter" objects that are responsible for moving the logging information out of good and to files, http endpoints, database, whatever the storage ends up being.

It is a hapi plugin and would be less than useless outside the context of hapi. It is not a general logging utility. 

We welcome and encourage any PR documentation that would help make using our modules easier!

**Comment by lloydbenson** [comment]
Why do I need good?

1.  Line 11 of the readme.
**good** is a process monitor that listens for one or more of the below 'event types'. All of these events, _except_ 'ops',  map to a hapi event documented [here](https://github.com/hapijs/hapi/blob/master/API.md#server-events).

2.  They are the same events, theres no better and thats also in the same readme line where it points to which hapi events specifically.

3.  It's a matter of preference, welcome to open source. This is a solution that was decided to be open sourced, which you can use, extend via reporters (which is documented), or certainly use any other module (or create your own).  There is alot of documentation in the readme to do whatever you want.

4.  It is a hapi plugin.  See http://hapijs.com/plugins.  It is under the hapijs umbrella so it is hapi related and only useful for hapi.  Since it ties again in that same documentation line to hapi events, it would obviously be only hapi related.

Well I understand documentation can always be better, I don't see specifics listed here to really help out.  If you have specifics, we certainly welcome any PRs to improve that.  I am closing this up but feel free to reopen it again if you have specifics here you'd like to address.
