### ISSUE TITLE
Good 7.x with winston 2.x

### ISSUE THREAD

**Issue by alexandrebodin** [hapijs/good#503]
Hello guys!

I just published a new adapter for winston that works with Good v7.x.

https://github.com/alexandrebodin/hapi-good-winston

Don't hesitate to open issues and give feedback !

**Comment by arb** [comment]
This isn't the place to open this issue. If you'd like this plugin listed somewhere, feel free to open a pull request over [here](https://github.com/hapijs/hapijs.com).

We don't really list community reporters/adapters anymore because it was a hassle to maintain and you can use any stream object(s) from npm now.

That being said, I'm sure this will be useful as I know people want to use winston and good together 👍
